// SPDX-FileCopyrightText: 2021 RizinOrg <info@rizin.re>
// SPDX-License-Identifier: LGPL-3.0-only
//
// WARNING: This file was auto-generated by CmdDescsGenerator.py script. Do not
// modify it manually. Look at cmd_descs.yaml if you want to update commands.
//

#include <rz_cmd.h>
#include <rz_core.h>
#include <rz_util.h>

// Command handlers, manually defined somewhere else
// "reai_hc"
RZ_IPI RzCmdStatus rz_health_check_handler(RzCore *core, int argc, const char **argv);
// "reai_up"
RZ_IPI RzCmdStatus rz_upload_bin_handler(RzCore *core, int argc, const char **argv);

// Main function that initialize the entire commands tree
RZ_IPI void rzshell_cmddescs_init(RzCore *core);
