// SPDX-FileCopyrightText: 2021 RizinOrg <info@rizin.re>
// SPDX-License-Identifier: LGPL-3.0-only
//
// WARNING: This file was auto-generated by CmdDescsGenerator.py script. Do not
// modify it manually. Look at cmd_descs.yaml if you want to update commands.
//

#include "CmdDescs.h"

static const RzCmdDescArg upload_bin_args[2];

static const RzCmdDescHelp reai_help = {
	.summary = "RevEngAI Plugin Commands",
};
static const RzCmdDescArg health_check_args[] = {
	{ 0 },
};
static const RzCmdDescHelp health_check_help = {
	.summary = "Check connection status with RevEngAI servers.",
	.args = health_check_args,
};

static const RzCmdDescArg upload_bin_args[] = {
	{
		.name = "file_path",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,
		.optional = false,

	},
	{ 0 },
};
static const RzCmdDescHelp upload_bin_help = {
	.summary = "Upload given binary to RevEngAI servers.",
	.args = upload_bin_args,
};

RZ_IPI void rzshell_cmddescs_init(RzCore *core) {
	RzCmdDesc *root_cd = rz_cmd_get_root(core->rcmd);
	rz_cmd_batch_start(core->rcmd);

	RzCmdDesc *reai_cd = rz_cmd_desc_group_new(core->rcmd, root_cd, "reai", NULL, NULL, &reai_help);
	rz_warn_if_fail(reai_cd);
	RzCmdDesc *health_check_cd = rz_cmd_desc_argv_new(core->rcmd, reai_cd, "reai_hc", rz_health_check_handler, &health_check_help);
	rz_warn_if_fail(health_check_cd);

	RzCmdDesc *upload_bin_cd = rz_cmd_desc_argv_new(core->rcmd, reai_cd, "reai_up", rz_upload_bin_handler, &upload_bin_help);
	rz_warn_if_fail(upload_bin_cd);
	rz_cmd_batch_end(core->rcmd);
}
