name: Build Windows

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup Visual Studio Developer Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Build project with Python venv
      run: |
        # Create and activate virtual environment
        python -m venv .venv
        .\.venv\Scripts\Activate.ps1
        
        # Install Python dependencies
        python -m pip install --upgrade pip
        python -m pip install pyyaml
        
        # Verify PyYAML is available
        python -c "import yaml; print('PyYAML is available in venv')"
        
        # Run the build script
        Set-ExecutionPolicy Bypass -Scope Process -Force
        .\Scripts\Build.ps1
      shell: powershell
      
    - name: Collect runtime binaries
      run: |
        New-Item -ItemType Directory -Force -Path "artifacts"
        
        $InstallPath = "$env:USERPROFILE\.local\RevEngAI\Rizin\Install"
        
        Write-Host "=== Contents of Install Directory ==="
        if (Test-Path $InstallPath) {
          Get-ChildItem -Recurse $InstallPath | Select-Object -First 30 | ForEach-Object { Write-Host $_.FullName }
          
          Write-Host "`n=== Collecting Our Built Libraries (.dll) ==="
          # Collect only our built libraries (exclude rizin system DLLs)
          Get-ChildItem -Recurse $InstallPath -Filter "*.dll" | Where-Object { 
            $_.Name -notlike "rz_*.dll" -and $_.Name -notlike "rizin*.dll" 
          } | ForEach-Object {
            Copy-Item $_.FullName "artifacts\"
            Write-Host "Copied DLL: $($_.Name)"
          }
          
          Write-Host "`n=== Collecting Our Built Import Libraries (.lib) ==="
          # Collect import libraries for our built libraries (exclude rizin system LIBs)
          Get-ChildItem -Recurse $InstallPath -Filter "*.lib" | Where-Object { 
            $_.Name -notlike "rz_*.lib" -and $_.Name -notlike "rizin*.lib" 
          } | ForEach-Object {
            Copy-Item $_.FullName "artifacts\"
            Write-Host "Copied LIB: $($_.Name)"
          }
          
          # Look specifically for the plugin in rizin plugin directory
          Write-Host "`n=== Looking for reai_rizin plugin ==="
          $RizinPluginFound = $false
          
          # Try to get plugin directory from rizin
          try {
            $RizinPluginDir = & "$InstallPath\bin\rizin.exe" -H RZ_USER_PLUGINS 2>$null
            if ($RizinPluginDir -and (Test-Path $RizinPluginDir)) {
              Write-Host "Rizin plugin directory: $RizinPluginDir"
              Get-ChildItem $RizinPluginDir -Filter "*reai*" -ErrorAction SilentlyContinue | ForEach-Object {
                Copy-Item $_.FullName "artifacts\"
                Write-Host "Copied rizin plugin from RZ_USER_PLUGINS: $($_.Name)"
                $RizinPluginFound = $true
              }
            }
          } catch {
            Write-Host "Could not get plugin directory from rizin command"
          }
          
          # Look specifically for cutter plugin
          Write-Host "`n=== Looking for reai_cutter plugin ==="
          $CutterPluginFound = $false
          
          # Try common cutter plugin directories
          $CutterPluginDirs = @(
            "$InstallPath\lib\cutter\plugins",
            "$InstallPath\share\cutter\plugins",
            "$env:APPDATA\cutter\plugins",
            "$env:LOCALAPPDATA\cutter\plugins",
            "$env:APPDATA\rizin\cutter\plugins\native"
          )
          
          foreach ($CutterDir in $CutterPluginDirs) {
            if (Test-Path $CutterDir) {
              Write-Host "Checking cutter plugin directory: $CutterDir"
              Get-ChildItem $CutterDir -Filter "*reai*" -ErrorAction SilentlyContinue | ForEach-Object {
                Copy-Item $_.FullName "artifacts\"
                Write-Host "Copied cutter plugin: $($_.Name)"
                $CutterPluginFound = $true
              }
            }
          }
          
          # If plugins not found in standard locations, search install path thoroughly
          if (-not $RizinPluginFound) {
            Write-Host "Searching install path for reai_rizin plugin..."
            Get-ChildItem -Recurse $InstallPath -Filter "*reai_rizin*" -ErrorAction SilentlyContinue | ForEach-Object {
              Copy-Item $_.FullName "artifacts\"
              Write-Host "Found rizin plugin in install path: $($_.Name)"
              $RizinPluginFound = $true
            }
          }
          
          if (-not $CutterPluginFound) {
            Write-Host "Searching install path for reai_cutter plugin..."
            Get-ChildItem -Recurse $InstallPath -Filter "*reai_cutter*" -ErrorAction SilentlyContinue | ForEach-Object {
              Copy-Item $_.FullName "artifacts\"
              Write-Host "Found cutter plugin in install path: $($_.Name)"
              $CutterPluginFound = $true
            }
          }
        } else {
          Write-Host "Install path not found: $InstallPath"
        }
        
        # Search build directories for any missed plugin files (.dll and .lib)
        Write-Host "`n=== Searching build directories for plugin files ==="
        $BuildRizinPluginFound = $false
        $BuildCutterPluginFound = $false
        
        # Search for rizin plugin in build directories
        Get-ChildItem -Recurse . -Filter "*reai_rizin*" -ErrorAction SilentlyContinue | ForEach-Object {
          if ($_.FullName -notlike "*artifacts*") {  # Don't copy from artifacts folder to itself
            Copy-Item $_.FullName "artifacts\" -ErrorAction SilentlyContinue
            Write-Host "Found rizin plugin in build: $($_.Name)"
            $BuildRizinPluginFound = $true
          }
        }
        
        # Search for cutter plugin in build directories
        Get-ChildItem -Recurse . -Filter "*reai_cutter*" -ErrorAction SilentlyContinue | ForEach-Object {
          if ($_.FullName -notlike "*artifacts*") {  # Don't copy from artifacts folder to itself
            Copy-Item $_.FullName "artifacts\" -ErrorAction SilentlyContinue
            Write-Host "Found cutter plugin in build: $($_.Name)"
            $BuildCutterPluginFound = $true
          }
        }
        
        # If still no plugins found, do a broader search
        if (-not ($BuildRizinPluginFound -and $BuildCutterPluginFound)) {
          Write-Host "Doing broader search for plugins in build directories..."
          Get-ChildItem -Recurse . -Filter "*.dll" -ErrorAction SilentlyContinue | Where-Object {
            ($_.Name -like "*reai*" -and ($_.Name -like "*rizin*" -or $_.Name -like "*cutter*" -or $_.Name -like "*plugin*")) -and
            $_.FullName -notlike "*artifacts*" -and 
            $_.FullName -notlike "*Dependencies*" -and
            $_.Name -notlike "rz_*.dll"
          } | ForEach-Object {
            Copy-Item $_.FullName "artifacts\" -ErrorAction SilentlyContinue
            Write-Host "Found potential plugin in build: $($_.Name)"
          }
        }
        
        # Search build directories for any missed reai library files
        Write-Host "`n=== Searching build directories for reai library files ==="
        @("*reai.dll", "*reai.lib") | ForEach-Object {
          Get-ChildItem -Recurse . -Filter $_ -ErrorAction SilentlyContinue | ForEach-Object {
            if ($_.FullName -notlike "*artifacts*") {  # Don't copy from artifacts folder to itself
              Copy-Item $_.FullName "artifacts\" -ErrorAction SilentlyContinue
              Write-Host "Found reai library: $($_.Name)"
            }
          }
        }
        
        Write-Host "`n=== Final Runtime Binaries ==="
        $files = Get-ChildItem "artifacts"
        if ($files) {
          $files | Sort-Object Name | ForEach-Object { Write-Host "$($_.Name) ($($_.Length) bytes)" }
          
          # Check if we have the essential files
          $hasReaiDll = $files | Where-Object { $_.Name -eq "reai.dll" }
          $hasRizinPlugin = $files | Where-Object { $_.Name -like "*reai_rizin*" -or ($_.Name -like "*reai*" -and $_.Name -like "*rizin*") }
          $hasCutterPlugin = $files | Where-Object { $_.Name -like "*reai_cutter*" -or ($_.Name -like "*reai*" -and $_.Name -like "*cutter*") }
          
          Write-Host "`n=== Build Summary ==="
          Write-Host "✅ reai.dll: $(if ($hasReaiDll) { 'Found' } else { 'MISSING' })"
          Write-Host "$(if ($hasRizinPlugin) { '✅' } else { '❌' }) Rizin Plugin: $(if ($hasRizinPlugin) { 'Found' } else { 'MISSING' })"
          Write-Host "$(if ($hasCutterPlugin) { '✅' } else { '❌' }) Cutter Plugin: $(if ($hasCutterPlugin) { 'Found' } else { 'MISSING' })"
          
          if (-not $hasRizinPlugin) {
            Write-Host "WARNING: reai_rizin plugin was not found! This is a critical issue."
          }
          if (-not $hasCutterPlugin) {
            Write-Host "WARNING: reai_cutter plugin was not found! This may be expected if BUILD_CUTTER_PLUGIN was OFF."
          }
          
          # Only fail if rizin plugin is missing (cutter plugin is optional)
          if (-not $hasRizinPlugin) {
            exit 1
          }
        } else {
          Write-Host "ERROR: No artifacts were collected!"
          exit 1
        }
      shell: powershell
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: reai-rz-windows-binaries
        path: artifacts/
        if-no-files-found: error